repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [types-PyYAML]
  - repo: local
    hooks:
      - id: hdae-scan
        name: hdae scan
        entry: python -m tools.hdae.cli scan --packs YAML-015,ERR-011,LOG-010
        language: system
        pass_filenames: false
