name: H-DAE

on:
  pull_request:
    branches:
      - 'track/hdae/**'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements-dev.txt'
      - name: Preflight
        run: scripts/ci/hdae_ci.sh preflight

  hdae-run:
    runs-on: ubuntu-latest
    needs: preflight
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements-dev.txt'
      - name: Verify
        run: scripts/ci/hdae_ci.sh verify
      - name: Scan
        run: scripts/ci/hdae_ci.sh scan
      - name: Propose (dry-run)
        run: scripts/ci/hdae_ci.sh propose-dry
      - name: Gate on unwaived L1 (PR footprint)
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          BASE_REF: ${{ github.base_ref }}
        run: scripts/ci/hdae_ci.sh gate
      - name: PR Comment
        if: ${{ success() }}
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          CI_ALLOW_PR_COMMENT: '1'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: scripts/ci/hdae_ci.sh comment
      - name: Collect artifacts
        if: always()
        run: scripts/ci/hdae_ci.sh artifacts
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hdae-artifacts
          path: .hdae-artifacts
