name: Rulebook

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/agents/**'
      - 'Meta.yaml'

permissions:
  contents: write

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Compile Rulebook
        run: |
          make ensure-dirs || true
          python urs.py compile --meta Meta.yaml --out docs/agents/Compiled.Rulebook.md --json-out docs/bundles/base.llbundle.json
      - name: Commit changes if any
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add docs/agents/Compiled.Rulebook.md docs/bundles/base.llbundle.json || true
          git diff --cached --quiet || git commit -m "chore(rulebook): compile on push to main"
          git push || true

